spring:
  profiles:
    active: @spring.profiles.active@
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
  datasource:
    platform: postgres
    url: @jdbc.url@
    username: @jdbc.username@
    password: @jdbc.password@
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: classpath:/liquibase/crate-test-db-scheme.xml
    enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: workman.askanio@gmail.com
    password: 12332166zZ
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.debug: true
    protocol: smtp
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB