spring:
  profiles:
    active: test
  liquibase:
    change-log: classpath:/liquibase/master.xml
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL